-- Teste123456!
INSERT INTO app_user (documento, email, email_verificado, foto_url, nome, "password", telefone, role) VALUES('2343185', 'andreytondo@alunos.utfpr.edu.br', false, NULL, 'Andrey Tondo', '$2a$10$PAT0Rh1KBwjnqaWvGKQgou5Mkjz1iIFJoasd1R9O.V546opfKmXrm', '46991379026', 'ROLE_ADMIN');
INSERT INTO app_user (documento, email, email_verificado, foto_url, nome, "password", telefone, role) VALUES('2343185', 'pedrozorel@alunos.utfpr.edu.br', false, NULL, 'Pedro Zorel', '$2a$10$PAT0Rh1KBwjnqaWvGKQgou5Mkjz1iIFJoasd1R9O.V546opfKmXrm', '46991379026', 'ROLE_ADMIN');
INSERT INTO app_user (documento, email, email_verificado, foto_url, nome, "password", telefone, role) VALUES('2343185', 'brunoruaro@alunos.utfpr.edu.br', false, NULL, 'Bruno Ruaro', '$2a$10$PAT0Rh1KBwjnqaWvGKQgou5Mkjz1iIFJoasd1R9O.V546opfKmXrm', '46991379026', 'ROLE_ADMIN');
INSERT INTO app_user (documento, email, email_verificado, foto_url, nome, "password", telefone, role) VALUES('2343185', 'felipevilhalva@alunos.utfpr.edu.br', false, NULL, 'Felipe Vilhalva', '$2a$10$PAT0Rh1KBwjnqaWvGKQgou5Mkjz1iIFJoasd1R9O.V546opfKmXrm', '46991379026', 'ROLE_ADMIN');
INSERT INTO app_user (documento, email, email_verificado, foto_url, nome, "password", telefone, role) VALUES('2343185', 'rafaelabandeira@alunos.utfpr.edu.br', false, NULL, 'Rafaela Bandeira', '$2a$10$PAT0Rh1KBwjnqaWvGKQgou5Mkjz1iIFJoasd1R9O.V546opfKmXrm', '46991379026', 'ROLE_ADMIN');
INSERT INTO app_user (documento, email, email_verificado, foto_url, nome, "password", telefone, role) VALUES('2343185', 'renancezarotto@alunos.utfpr.edu.br', false, NULL, 'Renan Cezarotto', '$2a$10$PAT0Rh1KBwjnqaWvGKQgou5Mkjz1iIFJoasd1R9O.V546opfKmXrm', '46991379026', 'ROLE_ADMIN');
insert into pais (nome, sigla) values('Brasil', 'BR');
insert into pais (nome, sigla) values('China', 'CN');
insert into pais (nome, sigla) values('Estados Unidos', 'EUA');
INSERT INTO cidade (estado, nome) VALUES('PR', 'Pato Branco');
INSERT INTO cidade (estado, nome) VALUES('PR', 'Francisco Beltrão');
INSERT INTO cidade (estado, nome) VALUES('PR', 'Coronel Vivida');
INSERT INTO cidade (estado, nome) VALUES('SC', 'Chapecó');
-- categorias
INSERT INTO category (description, icon, parent_id) VALUES('Ferramentas', 'pi pi-cog', NULL);
INSERT INTO category (description, icon, parent_id) VALUES('Componentes', 'pi pi-microchip', NULL);
INSERT INTO category (description, icon, parent_id) VALUES('Raspberry Pi', 'pi pi-desktop', NULL);
INSERT INTO category (description, icon, parent_id) VALUES('Arduino', 'pi pi-code', NULL);
INSERT INTO category (description, icon, parent_id) VALUES('Periféricos', 'pi pi-table', NULL);
INSERT INTO category (description, icon, parent_id) VALUES('Cabos', 'pi pi-link', NULL);
INSERT INTO category (description, icon, parent_id) VALUES('Prototipagem', 'pi pi-th-large', NULL);
INSERT INTO category (description, icon, parent_id) VALUES('Bateria e Carregadores', 'pi pi-bolt', NULL);
INSERT INTO category (description, icon, parent_id) VALUES('Motores', 'pi pi-car', NULL);
INSERT INTO category (description, icon, parent_id) VALUES('Material Expediente', 'pi pi-file', NULL);
INSERT INTO category (description, icon, parent_id) VALUES('Impressora 3D', 'pi pi-cog', NULL);
INSERT INTO category (description, icon, parent_id) VALUES('Lego', 'pi pi-th-large', NULL);
INSERT INTO category (description, icon, parent_id) VALUES('Mobilia', 'pi pi-table', NULL);
INSERT INTO category (description, icon, parent_id) VALUES('Displays e Iluminação ', 'pi pi-lightbulb', NULL);
INSERT INTO category (description, icon, parent_id) VALUES('Acessórios', 'pi pi-box', NULL);
-- subcategorias
INSERT INTO category (description, icon, parent_id) VALUES('Manuais', 'pi pi-wrench', 1);
INSERT INTO category (description, icon, parent_id) VALUES('Soldagem', 'pi pi-hammer', 1);
INSERT INTO category (description, icon, parent_id) VALUES('Elétricas', 'pi pi-bolt', 1);
INSERT INTO category (description, icon, parent_id) VALUES('Potenciômetros', 'pi pi-sliders-h', 2);
INSERT INTO category (description, icon, parent_id) VALUES('Sensores', 'pi pi-eye', 2);
INSERT INTO category (description, icon, parent_id) VALUES('Drivers', 'pi pi-file-check', 2);
INSERT INTO category (description, icon, parent_id) VALUES('Resistores', 'pi pi-minus', 2);
INSERT INTO category (description, icon, parent_id) VALUES('Circuitos Integrados', 'pi pi-microchip', 2);
INSERT INTO category (description, icon, parent_id) VALUES('Transistores', 'pi pi-arrows-h', 2);
INSERT INTO category (description, icon, parent_id) VALUES('Botões e Chaves', 'pi pi-power-off', 2);
INSERT INTO category (description, icon, parent_id) VALUES('Diodos', 'pi pi-arrow-right', 2);
INSERT INTO category (description, icon, parent_id) VALUES('Microcontroladores', 'pi pi-code', 2);
INSERT INTO category (description, icon, parent_id) VALUES('Capacitores', 'pi pi-cloud', 2);
INSERT INTO category (description, icon, parent_id) VALUES('Reguladores de Tensão', 'pi pi-ellipsis-h', 2);
INSERT INTO category (description, icon, parent_id) VALUES('Conectores', 'pi pi-sliders-v', 2);
INSERT INTO category (description, icon, parent_id) VALUES('Atuadores e Relés', 'pi pi-link', 2);
INSERT INTO category (description, icon, parent_id) VALUES('Módulos e Conversores', 'pi pi-sync', 2);
INSERT INTO category (description, icon, parent_id) VALUES('Placas', 'pi pi-sitemap', 3);
INSERT INTO category (description, icon, parent_id) VALUES('Acessórios', 'pi pi-box', 3);
INSERT INTO category (description, icon, parent_id) VALUES('Shields', 'pi pi-inbox', 4);
INSERT INTO category (description, icon, parent_id) VALUES('Placas', 'pi pi-sitemap', 4);
INSERT INTO category (description, icon, parent_id) VALUES('Drivers', 'pi pi-file-check', 9);
INSERT INTO category (description, icon, parent_id) VALUES('Servo Motor', 'pi pi-compass', 9);
INSERT INTO category (description, icon, parent_id) VALUES('LEDs', 'pi pi-sun', 14);
INSERT INTO category (description, icon, parent_id) VALUES('Displays', 'pi pi-desktop', 14);
INSERT INTO fornecedor (cnpj, email, endereco, estado, ie, nome_fantasia, observacao, razao_social, telefone, cidade_id, cep) VALUES('05982200000100', 'ids@ids.inf.br', 'Avenida Brasil 922', 'PR', null, 'IDS Software e Assessoria', NULL, 'IDS Desenvolvimento de Software e Assessoria Ltda', '554632258383', 1, NULL);
insert into item (name, description, price, category_id, type) values('Tesoura', null, 18.90, 16, 'DURABLE');
insert into item (name, description, price, category_id, type) values('Sugador de solda', null, 27.95, 17, 'DURABLE');
insert into item (name, description, price, category_id, type) values('Cabo P2', null, 15.00, 6, 'CONSUMABLE');
insert into item (name, description, price, category_id, type) values('HD Externo Seagate', '1TB - Stgx1000400', 409.00, 5, 'DURABLE');
INSERT INTO asset (item_id, location, serial_number) values (4, 'V109', '40328');
INSERT INTO asset (item_id, location, serial_number) values (4, 'V108', '40329');
INSERT INTO asset (item_id, location, serial_number) values (4, 'V106', '40330');
INSERT INTO asset (item_id, location, serial_number) values (4, 'V105', '40331');
INSERT INTO asset (item_id, location, serial_number) values (4, 'V104', '40332');
INSERT INTO purchase ("date",fornecedor_id,user_id) VALUES ('2025-10-29 13:29:00',1,1);
INSERT INTO purchase ("date",fornecedor_id,user_id) VALUES ('2025-10-30 23:43:25',1,1);
INSERT INTO purchase_item (price, quantity, item_id, purchase_id) VALUES (18.90,10.00,1,1);
INSERT INTO purchase_item (price, quantity, item_id, purchase_id) VALUES (18.90,10.00,1,1);
INSERT INTO purchase_item (price, quantity, item_id, purchase_id) VALUES (15.00,10.00,3,2);
INSERT INTO inventory (quantity,item_id) VALUES (20.00,1);
INSERT INTO inventory (quantity,item_id) VALUES (10.00,3);
INSERT INTO inventory_transaction (quantity,"type","date",inventory_id,user_id) VALUES (10.00,'PURCHASE','2025-10-30 23:43:25',1,1);
INSERT INTO inventory_transaction (quantity,"type","date",inventory_id,user_id) VALUES (10.00,'PURCHASE','2025-10-30 23:43:26',1,1);
INSERT INTO inventory_transaction (quantity,"type","date",inventory_id,user_id) VALUES (10.00,'PURCHASE','2025-10-30 23:43:25',2,1);
INSERT INTO solicitation ("date",user_id,description,observation) VALUES ('2025-10-30 23:50:39',1,NULL,NULL);
INSERT INTO solicitation_item (quantity,item_id,solicitation_id) VALUES (10.00,2,1);
INSERT INTO loan (deadline,loan_date,user_id,observation,ra_siape) values ('2025-11-30 00:00:00-03','2025-10-30 23:53:15-03',1,NULL,NULL);
INSERT INTO loan_item (quantity,"return",item_id,loan_id) values (5.00,false,3,1);